CREATE DATABASE Practice5;

CREATE TABLE t_board (
	iboard INT UNSIGNED PRIMARY key AUTO_INCREMENT,
	title VARCHAR(100) NOT NULL,
	ctnt VARCHAR(500) NOT NULL,
	regdt DATETIME DEFAULT NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

SELECT * FROM t_board;