DROP FUNCTION if EXISTS fn_GET_AGE;

DELIMITER $$
CREATE FUNCTION fn_GET_AGE (
	V_BIRTH_DATE CHAR(8)
) RETURNS INT
BEGIN
	DECLARE V_CURRENT_YEAR CHAR(4);
	DECLARE V_BIRTH_YEAR CHAR(4);
	DECLARE V_AGE INT;
	
	SELECT DATE_FORMAT(NOW(), '%Y'), LEFT(V_BIRTH_DATE, 4)
	INTO V_CURRENT_YEAR, V_BIRTH_YEAR;
	
	SELECT CAST(V_CURRENT_YEAR AS INT) - CAST(V_BIRTH_YEAR AS INT) + 1
	INTO V_AGE;
	
	RETURN V_AGE;
END $$
DELIMITER ;

SELECT fn_GET_AGE('19980226');